'use client';

import Link from 'next/link';
import { useCart } from '@/components/CartProvider';

const euros = (cents: number) => `${(cents / 100).toFixed(2).replace('.', ',')} €`;

export default function CartPage() {
  const { cart, ready, update, remove, clear } = useCart();
  if (!ready) return <main className="mx-auto max-w-5xl px-6 py-16">Cargando cesta…</main>;
  if (!cart || cart.items.length === 0) return <main className="mx-auto max-w-5xl px-6 py-16"><Link href="/" className="text-sm font-bold">← Seguir comprando</Link><h1 className="mt-8 font-serif text-5xl">Tu cesta está vacía.</h1><p className="mt-4 text-raiz-700">Añade productos orgánicos para comenzar tu pedido.</p><Link href="/#productos" className="mt-7 inline-block rounded-full bg-raiz-950 px-6 py-4 font-bold text-white">Ver productos</Link></main>;
  return <main className="mx-auto max-w-5xl px-6 py-12"><div className="flex items-center justify-between"><Link href="/" className="text-sm font-bold">← Seguir comprando</Link><button type="button" onClick={() => void clear()} className="text-sm font-bold text-raiz-coral">Vaciar cesta</button></div><h1 className="mt-8 font-serif text-5xl">Tu cesta</h1><section className="mt-8 space-y-4">{cart.items.map(item => <article key={item.productId} className="grid gap-4 rounded-2xl border border-raiz-200 bg-white p-4 sm:grid-cols-[120px_1fr_auto]"><img src={item.product.imageUrl} alt={item.product.name} className="h-28 w-full rounded-xl object-cover"/><div><h2 className="text-xl font-semibold">{item.product.name}</h2><p className="mt-1 text-raiz-700">{euros(item.product.price)} / unidad</p><div className="mt-4 flex items-center gap-3"><div className="rounded-full border border-raiz-200"><button type="button" onClick={() => void update(item.productId, item.quantity - 1)} className="px-3 py-2" aria-label={`Disminuir ${item.product.name}`}>−</button><span className="inline-block min-w-7 text-center font-bold">{item.quantity}</span><button type="button" onClick={() => void update(item.productId, item.quantity + 1)} disabled={item.quantity >= item.product.inventory} className="px-3 py-2 disabled:opacity-40" aria-label={`Aumentar ${item.product.name}`}>+</button></div><button type="button" onClick={() => void remove(item.productId)} className="text-sm font-bold text-raiz-coral">Eliminar</button></div></div><p className="self-start text-right font-bold">{euros(item.subtotal)}</p></article>)}</section><aside className="mt-8 ml-auto max-w-md rounded-2xl bg-raiz-100 p-6"><div className="flex justify-between text-lg"><span>Total</span><b>{euros(cart.total)}</b></div><Link href="/checkout" className="mt-5 block w-full rounded-full bg-amber-900 px-6 py-4 text-center font-bold text-white">Continuar al checkout →</Link></aside></main>;
}
